console.log("This is loaded from the external js");
alert("This is an alert!");
var name = "Sara Alfakey";
var school = "Philip O Berry";
let hobby = "Listening to Music";
console.log(`Name: ${name}`);
console.log(`School: ${school}`);
console.log(`Hobby: ${hobby}`);
document.getElementById("name").innerHTML = "<b>Name: </b>"+name;
document.getElementById("school").innerHTML = "<b>School: </b>"+school;
document.getElementById("hobby").innerHTML = "<b>Hobby: </b>"+hobby;
